# Generated by Django 5.1.2 on 2024-12-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='flight_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
