# Generated by Django 5.1.2 on 2024-12-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=100)),
                ('voucher_picture', models.ImageField(upload_to='images_voucher/')),
                ('percentage', models.IntegerField()),
                ('voucher_description', models.CharField()),
                ('voucher_flight_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='flights.flight', to_field='code')),
            ],
        ),
    ]
