# Generated by Django 5.1.2 on 2024-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('voucher_picture', models.ImageField(upload_to='images_voucher/')),
                ('percentage', models.IntegerField()),
                ('voucher_description', models.TextField()),
            ],
        ),
    ]
