# Generated by Django 5.1.2 on 2024-12-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_code'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_flight_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='flights.flight', to_field='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_description',
            field=models.CharField(),
        ),
    ]
