# Generated by Django 5.1.2 on 2024-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('type_of_info', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('info_picture', models.ImageField(upload_to='images_info/')),
                ('info_details', models.TextField()),
            ],
        ),
    ]
