# Generated by Django 5.1.2 on 2024-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinfo',
            name='markdown_content',
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='html_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
