# Generated by Django 5.1.2 on 2024-11-14 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_user_citizen_id_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('economic_seats', models.IntegerField()),
                ('business_seats', models.IntegerField()),
                ('economic_seats_info', models.JSONField(null=True)),
                ('business_seats_info', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('delay_status', models.IntegerField()),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=10)),
                ('ticket_class', models.CharField(choices=[('E', 'Economic'), ('B', 'Business')], default='E', max_length=1)),
                ('booker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
