# Generated by Django 5.1.2 on 2024-11-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='plane_id',
            new_name='plane',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='booker_id',
            new_name='booker',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
