# Generated by Django 5.1.2 on 2025-11-30 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_business_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='available_economic_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled', False)), fields=('flight', 'seat'), name='unique_active_seat_per_flight'),
        ),
    ]
