# Generated by Django 5.1.2 on 2024-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
