# Generated by Django 5.1.2 on 2024-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_ticket_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_price',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='flight',
            name='economic_price',
            field=models.IntegerField(default=5000000),
        ),
    ]
