# Generated by Django 5.1.2 on 2024-12-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_ticket_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
