# Generated by Django 5.1.2 on 2024-11-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_citizen_id_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='user_id',
            new_name='related_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personal_info_id',
            new_name='personal_info',
        ),
    ]
